--insert into ImageSources(DateCreated, SourceName)
--values
--(GETDATE(), 'File System'),
--(GETDATE(), 'External URL')

--insert into Images(DateCreated, ImageSourceEntityID, NameWithExt, ResourcePath, URL)
--values
--(GETDATE(), 1, '1.jpg', 'NA', 'NA'),
--(GETDATE(), 1, '2.jpg', 'NA', 'NA'),
--(GETDATE(), 1, '3.jpg', 'NA', 'NA'),
--(GETDATE(), 1, '4.jpg', 'NA', 'NA'),
--(GETDATE(), 1, '5.jpg', 'NA', 'NA'),
--(GETDATE(), 1, '6.jpg', 'NA', 'NA'),
--(GETDATE(), 1, '7.jpg', 'NA', 'NA'),
--(GETDATE(), 1, '8.jpg', 'NA', 'NA'),
--(GETDATE(), 1, '9.jpg', 'NA', 'NA'),
--(GETDATE(), 1, '10.jpg', 'NA', 'NA')